In [5]:
import pandas as pd
import glob

paths = glob.glob("/Users/divyajyoti/dev/grad/NLP/ANLP-ESG/data/processed/*/corpus_pages_clean_final.csv")

dfs = []
for p in paths:
    df = pd.read_csv(p)
    # derive company from folder name
    company = p.split("/")[-2].replace("_layout_all", "")
    df["company"] = company
    dfs.append(df)

corpus = pd.concat(dfs, ignore_index=True)

corpus.to_csv("/Users/divyajyoti/dev/grad/NLP/ANLP-ESG/data/processed/all_corpus_cleaned_final.csv", index=False)
corpus.head(100)

,report_name,year,page,page_text,company
0,Apple_2017_ESG_Report.pdf,2017,0,Environmental Responsibility Report 2017 Progr...,apple
1,Apple_2017_ESG_Report.pdf,2017,1,Resources Safer Materials Better Together : En...,apple
2,Apple_2017_ESG_Report.pdf,2017,2,"less of the planet, we’re asking more of ourse...",apple
3,Apple_2017_ESG_Report.pdf,2017,3,"Our new corporate campus, Apple Park, is on tr...",apple
4,Apple_2017_ESG_Report.pdf,2017,4,Climate Change How can we lead the fight again...,apple
...,...,...,...,...,...
95,Apple_2019_ESG_Report.pdf,2019,38,X Our water footprint shows us that we need to...,apple
96,Apple_2019_ESG_Report.pdf,2019,39,Water Treatment Manager at a Clean Water Progr...,apple
97,Apple_2019_ESG_Report.pdf,2019,40,Pursuing water stewardship. Water connects com...,apple
98,Apple_2019_ESG_Report.pdf,2019,41,Apple Champs-Élysées is expected to receive a ...,apple
99,Apple_2019_ESG_Report.pdf,2019,42,"Since 2017, 100 percent of supplier assembly s...",apple

In [7]:
import pandas as pd
import nltk
nltk.download('punkt')

df = pd.read_csv("/Users/divyajyoti/dev/grad/NLP/ANLP-ESG/data/processed/all_corpus_cleaned_final.csv")

def split_into_sentences(text):
    if pd.isna(text) or text.strip() == "":
        return []
    return nltk.sent_tokenize(text)

rows = []
for idx, row in df.iterrows():
    sentences = split_into_sentences(row["page_text"])
    
    for i, s in enumerate(sentences):
        rows.append({
            "company": row["company"],
            "report_name": row["report_name"],
            "year": row["year"],
            "page": row["page"],
            "sentence_id": i,
            "sentence_text": s.strip()
        })

sent_df = pd.DataFrame(rows)
sent_df.to_csv("/Users/divyajyoti/dev/grad/NLP/ANLP-ESG/data/processed/all_corpus_sentences.csv", index=False)

sent_df.tail()

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/divyajyoti/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,company,report_name,year,page,sentence_id,sentence_text
98365,microsoft,report_2021.pdf,2021,117,6,Sept-21 UK Filed response to UK Financial Cond...
98366,microsoft,report_2021.pdf,2021,117,7,Sept-21 US Submitted comments to the US Depart...
98367,microsoft,report_2021.pdf,2021,117,8,Oct-21 Global Joined business letter in suppor...
98368,microsoft,report_2021.pdf,2021,117,9,Oct-21 US Issued public statement in support o...
98369,microsoft,report_2021.pdf,2021,117,10,Nov-21 Global Selected as a Principal Partner ...